# This is a strip down rkcomp compatible Makefile.ker for generation
# of the main program. 
#

CTANGLE = $(OBJDIR)/ctangle

PROG = $(OBJDIR)/cweave

COBJ = common.o cweave.o

CWEBEES = cweave.c common.c

LIBES =

all: $(PROG)

CWEBINPUTS = $(SRCDIR)

cweave.c: cweave.w commonh.w cweave.ch
common.c: common.w commonh.w common.ch

$(PROG): $(CTANGLE)

